### ISSUE TITLE
Entitas Photon

### ISSUE THREAD

**Issue by optimisez** [RomanZhu/Entitas-Sync-Framework#2]
Hi @RomanZhu. Any plan to create new repo for photon support in Entitas?

**Comment by RomanZhu** [comment]
Hey.
I have no plans for Photon support.

What use case do you have?

**Comment by optimisez** [comment]
@RomanZhu. Currently I have realtime MOBA game project that using Photon to develop. I'm exploring how can I use Photon in Entitas.

**Comment by RomanZhu** [comment]
The current synchronization strategy requires a single source of authority, which is generally not the case with PUN. 
I don't know any good generic solutions for your case.
